version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "7-Tizain"
      - match:
          dependency_name: "7-rudolf101"
      - match:
          dependency_name: "7-zishkaz"
      - match:
          dependency_name: "7-SofuriHafe"
      - match:
          dependency_name: "7-ShishaK1N9"
      - match:
          dependency_name: "7-Mishavint"
      - match:
          dependency_name: "7-kettlberry"
      - match:
          dependency_name: "7-IAmFunkyFrog"
      - match:
          dependency_name: "7-esvault"
      - match:
          dependency_name: "7-danielsheh02"
      - match:
          dependency_name: "7-AzimMuradov"
      - match:
          dependency_name: "7-artmotika"
      - match:
          dependency_name: "7-TimPushkin"
      - match:
          dependency_name: "7-smmac72"
      - match:
          dependency_name: "7-Ramazanov-Amir"
      - match:
          dependency_name: "7-PyRayman"
      - match:
          dependency_name: "7-AShlegel"
    ignored_updates:
      - match:
          dependency_name: "7-sorter-utility"
